[template.environment]
GQL_HOST = "WordPress URL pu39v7rxsc-staging.wpdns.site/graphql"
NUXT_IMAGE_DOMAINS = "pu39v7rxsc-staging.wpdns.site"

[build]
command = "nuxt generate"

[images]
remote_images = ["https://pu39v7rxsc-staging.wpdns.site/.*"]
